-- ========================================================
-- Supabase Schema for RelV Portfolio Gallery Table
-- ========================================================

-- 1. Create Portfolio Gallery Table
CREATE TABLE IF NOT EXISTS public.portfolio_gallery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('projects', 'certificates', 'awards')),
    title TEXT NOT NULL,
    sub_category TEXT NOT NULL, -- e.g., 'Web Dev', 'Award - 2025', 'Certification'
    description TEXT NOT NULL,
    image_url TEXT, -- Nullable, will render placeholder if null
    github_url TEXT, -- Nullable, link to repository
    live_url TEXT, -- Nullable, link to live demo/website
    detail_url TEXT, -- Nullable, link to certificate/trophy image
    icon_type TEXT DEFAULT 'trophy', -- 'trophy', 'medal', 'award', 'certificate' (used if image_url is null)
    sort_order INTEGER DEFAULT 0 NOT NULL,
    is_visible BOOLEAN DEFAULT true NOT NULL
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.portfolio_gallery ENABLE ROW LEVEL SECURITY;

-- 3. Security Policies
-- Policy A: Allow anyone to read visible gallery items
CREATE POLICY "Allow public read access to gallery" 
ON public.portfolio_gallery 
FOR SELECT 
USING (is_visible = true OR auth.role() = 'authenticated');

-- Policy B: Allow logged-in admin full access (for dashboard management)
CREATE POLICY "Allow admin full access to gallery" 
ON public.portfolio_gallery 
FOR ALL 
TO authenticated 
USING (true) 
WITH CHECK (true);

-- 4. Initial Seed Data (Matching index.html static cards)
INSERT INTO public.portfolio_gallery (category, title, sub_category, description, image_url, github_url, live_url, detail_url, icon_type, sort_order) VALUES
('projects', 'OSIS Recruitment Selection Results System Using NextJS', 'Web Dev', 'Frontend using Next.js 14, React, Tailwind CSS and Database using Firebase. i built a web-based system inspired by the SNBP university selection portal, allowing candidates to securely check their results by entering their Registration ID and birth date. Successful candidates immediately receive their acceptance details along with a WhatsApp QR code to join the OSIS.', 'https://res.cloudinary.com/dvpq5fsef/image/upload/v1780841887/oa9tgxawjzxkszaqjmaa.webp', 'https://github.com/RelV-Dev', 'https://osissmaga.my.id/oprec/2025', NULL, 'trophy', 10),
('projects', 'Living Heritage: Digital Educational Platform of Pati Residency and Tjondronegoro Tomb', 'Web Dev', 'An educational web application that presents the historical and cultural heritage of the former Pati Residency, with a special focus on Makam Tjondronegoro as a central narrative. Built using HTML, CSS, and JavaScript with a fully responsive design, the website delivers structured historical content, visual storytelling, and intuitive navigation.', 'https://res.cloudinary.com/dvpq5fsef/image/upload/v1780841888/yh1vbcskffzakgup9z5p.webp', NULL, 'https://smanegeri3pati.site', NULL, 'trophy', 20),
('projects', 'IoT-Based Solar Energy Monitoring and Power Management System with API-Driven Dashboard Using Next.js', 'HARDWARE', 'An IoT-based mobile solar energy system that monitors temperature, voltage, and current in real time using ESP32 and cloud integration, enabling efficient power management and data visualization through a web dashboard.', 'https://res.cloudinary.com/dvpq5fsef/image/upload/v1780841889/outixtgzrumkdif8plch.webp', NULL, 'https://smanegeri3pati.site', NULL, 'trophy', 30),
('awards', '1st Place - National Scientific Paper Competition (LKTI) IEEE SB UB Fest 2025', 'Award - 2025', 'Dikeluarkan oleh IEEE Student Branch, Universitas Brawijaya. Awarded 1st Place at the National Level in the IEEE SB UB Fest 2025 organized by the IEEE Student Branch of Universitas Brawijaya, a chapter of the Institute of Electrical and Electronics Engineers (IEEE) - the world''s largest professional organization dedicated to advancing technology for humanity.', 'https://res.cloudinary.com/dvpq5fsef/image/upload/v1780841890/vr8n9ecgmxknyt3ugv9q.webp', NULL, NULL, 'https://github.com/RelV-Dev/Certificate/blob/main/FAREL_JUARA%201%20KTI%20TINGKAT%20NASIONAL%20IEEE%20FEST%20UNIVERSITAS%20BRAWIJAYA.webp', 'trophy', 40),
('awards', '1st Place Winner - Poster Design FLS3N', 'Award - 2025', 'Dikeluarkan oleh Kementerian Pendidikan, Kebudayaan, Riset, dan Teknologi (Kemendikbudristek). Created a visually impactful poster design that stood out among district-level participants in the FLS3N competition organized by the Indonesian Ministry of Education and Culture.', 'https://res.cloudinary.com/dvpq5fsef/image/upload/v1780841891/b0gjexr0kwsjdvopbyfg.webp', NULL, NULL, 'https://github.com/RelV-Dev/Certificate/blob/main/FAREL_PIAGAM%20FLS3N%20SMA%20KAB%20PATI%202025.webp', 'trophy', 50),
('awards', '2nd Place - National IoT Competition (IONIC 2025)', 'Award - 2025', 'Dikeluarkan oleh Politeknik Elektronika Negeri Surabaya (PENS). Represented SMA Negeri 3 Pati and was awarded 2nd Place in the Internet of Things (IoT) category at IONIC 2025, a national-level competition organized by PENS. PENS is ranked as the number one polytechnic in Southeast Asia and among the top 10 polytechnics in Asia.', 'https://res.cloudinary.com/dvpq5fsef/image/upload/v1780841892/ncd0az7irx4qecposbgq.webp', NULL, NULL, 'https://github.com/RelV-Dev/Certificate/blob/main/FAREL_JUARA%202%20IOT%20IONIC%202025.webp', 'trophy', 60),
('awards', '2nd Place – National App Development Competition (TechnoFair 2025)', 'Award - 2025', 'Dikeluarkan oleh panitia TechnoFair 2025. Awarded 2nd Place at the National Level in the App Development Competition at TechnoFair 2025, recognizing innovation, technical implementation, and problem-solving capabilities in mobile and application-based software development.', 'https://res.cloudinary.com/dvpq5fsef/image/upload/v1780841893/tasbvk8xwlygb71niqsz.webp', NULL, NULL, 'https://github.com/RelV-Dev/Certificate/blob/main/FAREL_JUARA%202%20TECHNOFAIR%20TINGKAT%20NASIONAL.webp', 'trophy', 70),
('awards', '3rd Place - Scientific Paper Competition (Physics & Applied Sciences)', 'Award - 2025', 'Dikeluarkan oleh Universitas Ahmad Dahlan (UAD) -Yogyakarta. Achieved 3rd place in the Provincial Level Scientific Paper Competition focusing on Physics and Applied Sciences.', 'https://res.cloudinary.com/dvpq5fsef/image/upload/v1780841894/e0wjlmiyh2lrhkzwrup5.webp', NULL, NULL, 'https://github.com/RelV-Dev/Certificate/blob/main/FAREL_JUARA%203%20KTI%20Tk.%20DIY-JATENG%20UNIVERSITAS%20AHMAD%20DAHLAN.webp', 'trophy', 80),
('awards', 'Google Kick Start 2021 – Round C (Global Rank 17)', 'Award – 2021', 'International competitive programming contest by Google, focused on advanced algorithms and problem-solving skills.', 'https://res.cloudinary.com/dvpq5fsef/image/upload/v1780841895/eofr2wy2ezeoagjcqyku.webp', NULL, NULL, 'https://github.com/RelV-Dev/Certificate/blob/main/FAREL_Google%20Kickstart%202021.webp', 'trophy', 90),
('awards', 'Juara Harapan 2 Karya Tulis Ilmiah (KRENOVA) Kabupaten Pati', 'Award – 2025', 'Diselenggarakan oleh Bappeda Kabupaten Pati. Juara Harapan 2 dalam Lomba Karya Tulis Ilmiah Kreativitas dan Inovasi Masyarakat (KRENOVA) Tingkat Kabupaten Pati bidang Rekayasa Energi Manufaktur.', NULL, NULL, NULL, NULL, 'trophy', 100),
('awards', 'Finalis KRENOVA Tingkat Provinsi Jawa Tengah', 'Award – 2025', 'Diselenggarakan oleh Brida Provinsi Jawa Tengah. Terpilih sebagai Finalis KRENOVA Tingkat Provinsi Jawa Tengah mewakili Kabupaten Pati.', NULL, NULL, NULL, NULL, 'award', 110),
('awards', 'Gold Medal Indonesian Advance Science Competition (IASC)', 'Award – 2025', 'Diselenggarakan oleh Fosnas. Meraih Medali Emas (Gold Medal) tingkat nasional dalam Indonesian Advance Science Competition (IASC) di bidang Informatika.', NULL, NULL, NULL, NULL, 'medal', 120),
('certificates', 'Data Science', 'Certification', 'Professional data science certification by MITx delivered through the edX platform.', 'https://res.cloudinary.com/dvpq5fsef/image/upload/v1780841896/rnbkrgr2xn6mtapdcrxd.webp', NULL, NULL, 'https://github.com/RelV-Dev/Certificate/blob/main/FAREL_EDX%20MIT%20DATA%20SCIENCE.webp', 'certificate', 130),
('certificates', 'Data Science & Machine Learning', 'Certification', 'Professional certification in data analysis and machine learning by HarvardX via edX.', 'https://res.cloudinary.com/dvpq5fsef/image/upload/v1780841897/ztibnx6pxrgei5bwalee.webp', NULL, NULL, 'https://github.com/RelV-Dev/Certificate/blob/main/FAREL_EDX_HARVARD_1027168179162.webp', 'certificate', 140),
('certificates', 'Python Programming', 'Certification', 'Python programming training provided by the Ministry of Communication and Informatics of Indonesia.', 'https://res.cloudinary.com/dvpq5fsef/image/upload/v1780841898/zvtmyommhql72wewcwze.webp', NULL, NULL, 'https://github.com/RelV-Dev/Certificate/blob/main/FAREL_KOMINFO_Python%20Program%20Online%20Academy.webp', 'certificate', 150),
('certificates', 'Digital Skills', 'Certification', 'National digital competency training covering modern technology and productivity tools.', 'https://res.cloudinary.com/dvpq5fsef/image/upload/v1780841898/uhcdv1fjmassewmhciwt.webp', NULL, NULL, 'https://github.com/RelV-Dev/Certificate/blob/main/FAREL_KOMINFO_DIGITAL%20SKILLS%20ONLINE%20ACADEMY.webp', 'certificate', 160);
