-- ========================================================
-- Supabase Schema for RelV Portfolio Testimonials Table
-- ========================================================

-- 1. Create Testimonials Table
CREATE TABLE IF NOT EXISTS public.testimonials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    customer_name TEXT NOT NULL,
    project_title TEXT NOT NULL,
    category TEXT NOT NULL,
    price BIGINT DEFAULT 0 NOT NULL,
    transfer_proof TEXT,
    project_proof TEXT,
    chat_screenshot TEXT,
    project_link TEXT,
    demo_video_url TEXT,
    proof_type TEXT NOT NULL,
    transaction_date DATE,
    is_visible BOOLEAN DEFAULT true NOT NULL
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;

-- 3. Security Policies
-- Policy A: Allow anyone to read visible testimonials (for frontend portfolio display)
CREATE POLICY "Allow public read access" 
ON public.testimonials 
FOR SELECT 
USING (is_visible = true OR auth.role() = 'authenticated');

-- Policy B: Allow logged-in admin full access (for dashboard management)
CREATE POLICY "Allow admin full access" 
ON public.testimonials 
FOR ALL 
TO authenticated 
USING (true) 
WITH CHECK (true);
